server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ddewaele/spring-cloud-config-repo
          basedir: target/config  # avoid /tmp getting wiped out containing the cloned repo.
#          uri: git@github.com:ddewaele/spring-cloud-config-repo-private.git
#          username: ddewaele
#          password: strong_password
#          cloneOnStart: true

encrypt:
#  keyStore:
#    location: classpath:/server.jks
#    password: letmein
#    alias: mytestkey
#    secret: changeme
  key: mysecret

server:
  port: 8888

