server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
#          basedir: target/config  # avoid /tmp getting wiped out containing the cloned repo.
          uri: https://github.com/ddewaele/spring-cloud-config-repo.git
          cloneOnStart: true
        default-label: branch1

encrypt:
  key: mysecret
#  key-store:
#    location: classpath:/server.jks
#    password: letmein
#    alias: mytestkey
#    secret: changeme
